export const SUBREDDIT_CATEGORIES = {
  Animals: ["aww","Eyebleach","AnimalsBeingDerps","Zoomies","RarePuppers","BabyElephantGifs","Capybara","PartyParrot"],
  Nature: ["EarthPorn","CozyPlaces","FairytaleAsFuck","Skyporn","NationalPark","Cottagecore","ForestPorn","MiniWorlds"],
  Sports: ["nba","nfl","soccer","formula1","baseball","hockey","tennis","golf","SportsAreAwesome","nextlevel"],
  Music: ["MusicPorn","LofiHipHop","vinyl","listentothis","InstrumentPorn","classicalmusic","AlbumArtPorn","StreetMusicians"],
  Food: ["FoodPorn","Baking","Coffee","tea","CulinaryPlating","Breadit","Charcuterie","Pizza"],
  "Art & Design": ["museum","PixelArt","ArchitecturePorn","Satisfyingasfuck","Watercolor","DesignPorn","ImaginarySliceOfLife","Handwriting"],
  Science: ["spaceporn","dataisbeautiful","JamesWebbTelescope","Awwducational","MicroPorn","astronomy","EverythingScience"],
  Uplifting: ["HumansBeingBros","MadeMeSmile","UpliftingNews","dadreflexes","BenignExistence","decidingtobebetter","OldSchoolCool"],
  "Global/Wonder": ["TravelPorn","VillagePorn","CityPorn","StreetPorn","MapPorn","todayilearned","BeAmazed"],
  "Zen": ["Zen","Buddhism","Meditation","Mindfulness","DailyZen","JapaneseGardens","Stoicism","WabiSabi"],
  "Travel": ["RemotePlaces","TravelPhotos","SlowTravel","DigitalNomad","LuxuryTravel"],
};

export const ALL_SUBREDDITS = Object.values(SUBREDDIT_CATEGORIES).flat();

export const SUBREDDIT_TO_CATEGORY = Object.entries(SUBREDDIT_CATEGORIES).reduce(
  (acc, [cat, subs]) => { subs.forEach((s) => { acc[s.toLowerCase()] = cat; }); return acc; },
  {}
);

// ── FEED MODES ─────────────────────────────────────────────
export const FEED_MODES = [
  {
    id: "my-morning",
    label: "My Morning",
    font: "'Cormorant Garamond', serif",
    fontWeight: 300,
    fontSize: "15px",
    letterSpacing: "0.3px",
    fontStyle: "normal",
    colorActive: "#5c2d4a",
    bgActive: "#e8c8d8",
    colorInactive: "#b08a9e",
    borderInactive: "#e2c8d4",
    categories: null,
  },
  {
    id: "drift",
    label: "Drift",
    font: "'Lora', serif",
    fontWeight: 400,
    fontSize: "14px",
    letterSpacing: "0px",
    fontStyle: "italic",
    colorActive: "#5a3e04",
    bgActive: "#f5d888",
    colorInactive: "#a07820",
    borderInactive: "#e8c870",
    categories: null,
    allSubs: true,
  },
  {
    id: "gentle",
    label: "Gentle",
    font: "'Cormorant Garamond', serif",
    fontWeight: 300,
    fontSize: "15px",
    letterSpacing: "0.3px",
    fontStyle: "normal",
    colorActive: "#1a0a3c",
    bgActive: "#c8b8f0",
    colorInactive: "#6a4ab0",
    borderInactive: "#b8a0e0",
    categories: ["Zen", "Nature", "Animals", "Uplifting"],
  },
  {
    id: "plugged-in",
    label: "Plugged In",
    font: "'Barlow Condensed', sans-serif",
    fontWeight: 600,
    fontSize: "13px",
    letterSpacing: "1px",
    fontStyle: "normal",
    textTransform: "uppercase",
    colorActive: "#0d1f3c",
    bgActive: "#c0cce0",
    colorInactive: "#4a5a7a",
    borderInactive: "#a0aec0",
    categories: ["Science", "Global/Wonder"],
    includeNews: true,
  },
  {
    id: "curious",
    label: "Curious",
    font: "'DM Sans', sans-serif",
    fontWeight: 500,
    fontSize: "13px",
    letterSpacing: "0.2px",
    fontStyle: "normal",
    colorActive: "#0f4a3e",
    bgActive: "#b8e0d8",
    colorInactive: "#3a8a7a",
    borderInactive: "#9fd4c8",
    categories: ["Art & Design", "Music", "Food", "Travel", "Global/Wonder"],
  },
  {
    id: "sports",
    label: "Sports",
    font: "'Barlow Condensed', sans-serif",
    fontWeight: 700,
    fontSize: "14px",
    letterSpacing: "1.2px",
    fontStyle: "normal",
    textTransform: "uppercase",
    colorActive: "#4a0a0a",
    bgActive: "#f0a8a8",
    colorInactive: "#b04a4a",
    borderInactive: "#e0a0a0",
    categories: ["Sports"],
  },
];
